Delete Hand
DELETE Game
DELETE Game_Player
DELETE Game_Planet
DELETE Game_Deck
DELETE GameTable
DELETE Deck_Card
DELETE Deck
DELETE Match_Player
DELETE Player_Card
DELETE Planet
DELETE Player
DELETE Card
DELETE Image
DELETE Country
DELETE CardType
DELETE PlanetType
DELETE Race
Delete CardType