Delete Hand
Delete Hand_Card
DELETE Deck_Card
DELETE Deck
DELETE Game
DELETE Game_Deck_Card
DELETE Game_Player
DELETE GameTable
DELETE Game_Deck
DELETE Match_Player
DELETE Player_Card
DELETE Planet
DELETE Player
DELETE Card
DELETE Image
DELETE Country
DELETE CardType
DELETE PlanetType
DELETE Race
Delete CardType