-- Create database StarDeck
Use StarDeck

CREATE TABLE CardType (
	id INT NOT NULL IDENTITY(1,1),
    typeName VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY (id)
)

CREATE TABLE Race(
	id INT NOT NULL IDENTITY(1,1),
    name VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY (id)
)

CREATE TABLE PlanetType(
	id INT NOT NULL IDENTITY(1,1),
	typeName VARCHAR(30) UNIQUE NOT NULL,
	PRIMARY KEY (id)
)

CREATE Table Country
(
	id INT NOT NULL IDENTITY(1,1),
	countryName VARCHAR(30) UNIQUE NOT NULL,
	PRIMARY KEY(id)
)

CREATE TABLE Image(
	id INT NOT NULL IDENTITY(1,1),
	imageString VARCHAR(MAX) NOT NULL,
	PRIMARY KEY(id)
)

CREATE TABLE Card (
    id VARCHAR(15) NOT NULL,
    name VARCHAR(30) NOT NULL,
    energy INT NOT NULL,
    cost INT NOT NULL,
    typeId INT NOT NULL,
    raceId INT NOT NULL,
    activatedCard BIT NOT NULL DEFAULT 1,
    description VARCHAR(1000), 
	imageId INT ,
    PRIMARY KEY (id)
)

CREATE TABLE Player
(
	id VARCHAR(15) NOT NULL,
	email VARCHAR(30) NOT NULL,
	firstName VARCHAR(15) NOT NULL,
	lastName VARCHAR(15) NOT NULL,
	username VARCHAR(15) NOT NULL,
	pHash VARCHAR(1000) NOT NULL,
	ranking VARCHAR(15) NOT NULL,
	xp INT NOT NULL,
	inGame BIT NOT NULL,
	activatedAccount BIT NOT NULL,
	countryId INT Not NULL,
	coins INT NOT NULL,
	avatarId INT NOT NULL,
	PRIMARY KEY(id)
)

CREATE TABLE Planet
(
	id VARCHAR(15) NOT NULL,
	name VARCHAR(15) NOT NULL,
	typeId int NOT NULL,
	activatedPlanet BIT DEFAULT 1 NOT NULL,
	description VARCHAR(1000),
	imageId INT,
	PRIMARY KEY(id)
)

CREATE TABLE Player_Card
(
	playerId VARCHAR(15) NOT NULL,
	cardId VARCHAR(15) NOT NULL,
	PRIMARY KEY(playerId, cardId)
)


CREATE TABLE Deck(
	id VARCHAR(15) NOT NULL,
	name VARCHAR(15) NOT NULL,
	playerId VARCHAR(15) NOT NULL,
	PRIMARY KEY (id)
)

CREATE TABLE Deck_Card (
    deckId VARCHAR(15) NOT NULL,
    cardId VARCHAR(15) NOT NULL,
    PRIMARY KEY (deckId, cardId)
)

CREATE TABLE SetupParam(
	id INT NOT NULL IDENTITY(1,1),
	totalTurns INT NOT NULL,
	turnTime INT NOT NULL,
	PRIMARY KEY (id)
)

CREATE TABLE Match_Player(
	id VARCHAR(15) NOT NULL,
	waiting_since VARCHAR(15) NOT NULL,
)

CREATE TABLE Game_Planets(
	gameId VARCHAR(15) NOT NULL,
	planetId VARCHAR(15) NOT NULL,
)

CREATE TABLE Game(
	id VARCHAR(15) NOT NULL,
	player1Id VARCHAR(15) NOT NULL,
	player2Id VARCHAR(15) NOT NULL,
	PRIMARY KEY (id)
)


-- CREATE FOREIGN KEYS
ALTER TABLE Card
ADD CONSTRAINT fk_Card_Race
FOREIGN KEY (raceId)
REFERENCES Race(id);

ALTER TABLE Card
ADD CONSTRAINT fk_Card_Type
FOREIGN KEY (typeId)
REFERENCES CardType(id);

ALTER TABLE Card
ADD CONSTRAINT fk_Card_Image
FOREIGN KEY (imageId)
REFERENCES Image(id);

ALTER TABLE Player
ADD CONSTRAINT fk_Country_Player
FOREIGN KEY (countryId)
REFERENCES Country(id)

ALTER TABLE Planet
ADD CONSTRAINT fk_PlanetType_Planet
FOREIGN KEY (typeId)
REFERENCES PlanetType(id)

ALTER TABLE Planet
ADD CONSTRAINT fk_Planet_Image
FOREIGN KEY (imageId)
REFERENCES Image(id)

ALTER TABLE Player
ADD CONSTRAINT fk_Player_Image
FOREIGN KEY (avatarId)
REFERENCES Image(id)

ALTER TABLE Player_Card
ADD CONSTRAINT fk_Card_Player
FOREIGN KEY (cardId)
REFERENCES Card(id)

ALTER TABLE Player_Card
ADD CONSTRAINT fk_Player_Card
FOREIGN KEY (playerId)
REFERENCES Player(id)

ALTER TABLE Deck
ADD CONSTRAINT fk_Deck_Player
FOREIGN KEY (playerId)
REFERENCES Player(id)

ALTER TABLE Deck_Card
ADD CONSTRAINT fk_Deck_Card
FOREIGN KEY (cardId)
REFERENCES Card(id);

ALTER TABLE Deck_Card
ADD CONSTRAINT fk_Card_Deck
FOREIGN KEY (deckId)
REFERENCES Deck(id);

ALTER TABLE Match_Player
ADD CONSTRAINT fk_Player_Match
FOREIGN KEY (id)
REFERENCES Player(id);

ALTER TABLE Game_Planets
ADD CONSTRAINT fk_Game_Planet
FOREIGN KEY (gameId)
REFERENCES Game(id);

ALTER TABLE Game_Planets
ADD CONSTRAINT fk_Planet_Game
FOREIGN KEY (planetId)
REFERENCES Planet(id);

ALTER TABLE Game
ADD CONSTRAINT fk_Player1_Game
FOREIGN KEY (player1Id)
REFERENCES Player(id);

ALTER TABLE Game
ADD CONSTRAINT fk_Player2_Game
FOREIGN KEY (player2Id)
REFERENCES Player(id);

